# Generated by Django 4.2.30 on 2026-08-26 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualizar', '0002_userprofile_gems_userprofile_last_activity_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_design', models.IntegerField(default=5, help_text='Avaliação do Design Visual e Conceito Minimalista')),
                ('rating_colors', models.IntegerField(default=5, help_text='Paleta de Cores e Conforto Visual')),
                ('rating_typography', models.IntegerField(default=5, help_text='Tipografia e Legibilidade')),
                ('rating_usability', models.IntegerField(default=5, help_text='Usabilidade e Navegação')),
                ('rating_vocational_test', models.IntegerField(default=5, help_text='Experiência no Teste Vocacional e Autoconhecimento')),
                ('rating_responsiveness', models.IntegerField(default=5, help_text='Responsividade e Desempenho')),
                ('overall_rating', models.IntegerField(default=5, help_text='Satisfação Geral com a Plataforma')),
                ('favorite_feature', models.CharField(blank=True, help_text='Recurso Favorito', max_length=150, null=True)),
                ('suggestions', models.TextField(blank=True, help_text='Comentários e Sugestões de Melhoria', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
