# Generated by Django 4.2.30 on 2026-08-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizar', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='age',
            field=models.IntegerField(blank=True, help_text='Idade do usuário', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_working',
            field=models.CharField(blank=True, help_text='Já atua profissionalmente?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='work_experience_time',
            field=models.CharField(blank=True, help_text='Tempo de atuação profissional', max_length=100, null=True),
        ),
    ]
