# Generated by Django 4.2.30 on 2026-04-25 02:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaVisita',
            fields=[
                ('id_categoria_visita', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('cnpj', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelTecnico',
            fields=[
                ('id_resp_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', django_cryptography.fields.encrypt(models.CharField(max_length=14, unique=True))),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_doc', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('prazo_validade_meses', models.IntegerField()),
                ('obrigatorio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('data_evento', models.DateField()),
                ('observacao', models.TextField()),
                ('fk_categoria_visita', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.categoriavisita')),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.empresa')),
                ('fk_resp_tecnico_historico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.responsaveltecnico')),
            ],
        ),
        migrations.CreateModel(
            name='NecessidadeDocumento',
            fields=[
                ('id_necessidade', models.AutoField(primary_key=True, serialize=False)),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades_documento', to='core.empresa')),
                ('fk_tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(help_text='ID do registro afetado')),
                ('tipo', models.CharField(help_text='Ex: Inserir, Alterar, Deletar', max_length=50)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('fk_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaDocumento',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrega', models.DateField()),
                ('data_vencimento_calculada', models.DateField(blank=True, null=True)),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_documento', to='core.empresa')),
                ('fk_resp_tecnico_entrega', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.responsaveltecnico')),
                ('fk_tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.tipodocumento')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_resp_tecnico_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='empresas_atuais', to='core.responsaveltecnico'),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', django_cryptography.fields.encrypt(models.CharField(max_length=14))),
                ('data_entrada', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='core.empresa')),
            ],
        ),
    ]
