# Generated by Django 4.2.25 on 2026-05-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='inspecoes/'),
        ),
    ]
