# Generated by Django 4.2.25 on 2026-05-14 22:10

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visita_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=14, null=True, unique=True)),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
