# Generated by Django 4.2.30 on 2026-06-13 17:03

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_area_usuario_cpf_usuario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsaveltecnico',
            name='cpf',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=14)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=14, null=True)),
        ),
    ]
