# Generated by Django 4.2.30 on 2026-06-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_responsaveltecnico_cpf_alter_usuario_cpf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaVisita',
            new_name='TipoInspecao',
        ),
        migrations.RenameField(
            model_name='tipoinspecao',
            old_name='id_categoria_visita',
            new_name='id_tipo_inspecao',
        ),
        migrations.RenameField(
            model_name='visita',
            old_name='fk_categoria_visita',
            new_name='fk_tipo_inspecao',
        ),
    ]
