# Generated by Django 4.2.30 on 2026-06-24 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_categoriavisita_tipoinspecao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fk_resp_tecnico_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empresas_atuais', to='core.responsaveltecnico'),
        ),
    ]
