# Generated by Django 4.2.30 on 2026-06-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_empresa_fk_resp_tecnico_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregadocumento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
